# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f4b5fcf33ef51f8664b77a875aaa76f2216b07e41098c8b9e83a9fdc238bb2cc70b33d323cc61d9531b21e4749a066330decbf05abe3b4a7b417885e2dc17454

test:
  secret_key_base: aaf1c8af21b982eccf5c594c199d7fa00c6300d6fd21575b94185f7f98979a2b33b813052f7bc02c79203a5dc3c38cdbed4dd101a339874cb40de23d3a9eb38c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
